Repository ctalkington/python-ipp, pull requests merged in 2023-05, with the labels that each got.

#432 Improvements to serializer
  src/pyipp/serializer.py
  src/pyipp/tags.py
  tests/test_serializer.py
Labels: enhancement, maintenance

#433 Improve typing
  .pre-commit-config.yaml
  src/pyipp/models.py
  tests/__init__.py
  tests/test_models.py
Labels: enhancement, maintenance

#434 Define exports
  src/pyipp/__init__.py
Labels: maintenance

#411 Allow for markers and URIs being single values
  src/pyipp/models.py
Labels: bugfix

#438 Improve models test coverage
  tests/test_models.py
Labels: maintenance

#437 Refactor models
  src/pyipp/models.py
Labels: enhancement, maintenance

#429 Development workflow updates
  .devcontainer/devcontainer.json
  .flake8
  .github/workflows/linting.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  .isort.cfg
  .nvmrc
  .pre-commit-config.yaml
  examples/debug.py
  examples/printer.py
  examples/ruff.toml
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  src/pyipp/exceptions.py
  src/pyipp/ipp.py
  src/pyipp/parser.py
  src/pyipp/py.typed
  src/pyipp/serializer.py
  tests/fixtures/serializer/get-printer-attributes-request-000.bin
  tests/ruff.toml
  tests/test_client.py
  tests/test_interface.py
  tests/test_parser.py
  tests/test_serializer.py
Labels: maintenance, ci, github_actions

#439 Add example for executing operation
  examples/execute.py
Labels: documentation
