Repository ctalkington/python-ipp, pull requests merged in 2024-05, with the labels that each got.

#564 Use trusted publisher for release workflow
  .github/workflows/release.yml
Labels: ci

#553 Allow passing IPP version to IPP dataclass
  src/pyipp/ipp.py
Labels: new-feature

#571 Use syrupy snapshots for parser tests
  poetry.lock
  pyproject.toml
  tests/__snapshots__/test_parser.ambr
  tests/test_parser.py
Labels: ci

#572 Fix parsing of IPP collections
  src/pyipp/parser.py
  tests/__snapshots__/test_parser.ambr
Labels: bugfix

#573 Parse more enums to python enums
  src/pyipp/enums.py
  src/pyipp/parser.py
  tests/__snapshots__/test_parser.ambr
Labels: enhancement

#510 Support appending pre-encoded data when serializing
  examples/print_example.py
  src/pyipp/serializer.py
Labels: enhancement
